"""
topology_loader.py — Auto-Derive Network Topology from ANY net.xml
=====================================================================
Replaces the hardcoded ADJACENCY / ALL_NODES / RSU_LAYOUT dicts that
were hand-typed for your original 13-junction grid. Run this ONCE per
network, and it writes topology_cache.py — a plain importable module
that train_ppo.py, baseline_dqn.py, baseline_marl.py, and multi_rsu.py
can import from instead of defining their own hardcoded dicts.

This is what makes swapping networks (MoST, InTAS, or anything else
later) a one-command operation instead of a manual rewrite of five files.

Usage:
    python topology_loader.py --net most_package/in/most.net.xml --rsu-count 4

Output:
    topology_cache.py   (ADJACENCY, ALL_NODES, RSU_LAYOUT, RSU_NEIGHBORS)
"""

import argparse
import json
from pathlib import Path

import numpy as np
import sumolib


# ── Minimal k-means (Lloyd's algorithm) — no sklearn dependency ──────────────
def kmeans(points: np.ndarray, k: int, iters: int = 50, seed: int = 0):
    rng = np.random.RandomState(seed)
    idx = rng.choice(len(points), k, replace=False)
    centroids = points[idx].copy()
    labels = np.zeros(len(points), dtype=int)
    for _ in range(iters):
        d = np.linalg.norm(points[:, None, :] - centroids[None, :, :], axis=2)
        labels = d.argmin(axis=1)
        new_centroids = np.array([
            points[labels == i].mean(axis=0) if (labels == i).any() else centroids[i]
            for i in range(k)
        ])
        if np.allclose(new_centroids, centroids):
            break
        centroids = new_centroids
    return labels, centroids


def build_topology(net_file: str, rsu_count: int = 4, seed: int = 0):
    print(f"Loading network: {net_file}")
    net = sumolib.net.readNet(net_file)

    nodes = net.getNodes()
    edges = [e for e in net.getEdges() if not e.isSpecial()]
    print(f"  {len(nodes)} junctions, {len(edges)} routable edges")

    # ── ADJACENCY: node -> list of directly-reachable neighbour nodes ────
    adjacency = {}
    for e in edges:
        u, v = e.getFromNode().getID(), e.getToNode().getID()
        adjacency.setdefault(u, [])
        if v not in adjacency[u]:
            adjacency[u].append(v)

    all_nodes = [n.getID() for n in nodes]  # includes pure-sink nodes too

    # ── RSU regions via geographic k-means clustering ─────────────────────
    coords = {n.getID(): n.getCoord() for n in nodes}
    pts = np.array([coords[nid] for nid in all_nodes])
    labels, centroids = kmeans(pts, rsu_count, seed=seed)

    node_region = {all_nodes[i]: int(labels[i]) for i in range(len(all_nodes))}

    rsu_layout = {}
    for r in range(rsu_count):
        rname = f"RSU_{r}"
        region_nodes = [nid for nid, lbl in node_region.items() if lbl == r]
        region_edges = [
            e.getID() for e in edges
            if node_region.get(e.getFromNode().getID()) == r
        ]
        cx, cy = centroids[r]
        rsu_layout[rname] = dict(
            x=round(float(cx), 1), y=round(float(cy), 1),
            nodes=region_nodes, edges=region_edges,
        )
        print(f"  {rname}: {len(region_nodes)} junctions, "
              f"{len(region_edges)} edges, centroid=({cx:.0f},{cy:.0f})")

    # ── RSU adjacency mesh: connect each region to its 2 nearest neighbours ──
    rsu_ids = list(rsu_layout.keys())
    rsu_neighbors = {}
    for r1 in rsu_ids:
        dists = []
        for r2 in rsu_ids:
            if r1 == r2:
                continue
            d = np.hypot(rsu_layout[r1]["x"] - rsu_layout[r2]["x"],
                         rsu_layout[r1]["y"] - rsu_layout[r2]["y"])
            dists.append((d, r2))
        dists.sort()
        n_neighbors = min(2, len(dists))
        rsu_neighbors[r1] = [r2 for _, r2 in dists[:n_neighbors]]

    return adjacency, all_nodes, rsu_layout, rsu_neighbors


def write_cache(adjacency, all_nodes, rsu_layout, rsu_neighbors, out_path: str):
    with open(out_path, "w") as f:
        f.write('"""\nAUTO-GENERATED by topology_loader.py -- do not hand-edit.\n')
        f.write('Regenerate with: python topology_loader.py --net <path/to/net.xml>\n"""\n\n')
        f.write(f"ADJACENCY = {json.dumps(adjacency, indent=2)}\n\n")
        f.write(f"ALL_NODES = {json.dumps(all_nodes, indent=2)}\n\n")
        f.write(f"RSU_LAYOUT = {json.dumps(rsu_layout, indent=2)}\n\n")
        f.write(f"RSU_NEIGHBORS = {json.dumps(rsu_neighbors, indent=2)}\n")
    print(f"\nSaved -> {out_path}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--net", required=True, help="Path to a SUMO .net.xml file")
    p.add_argument("--rsu-count", type=int, default=4)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--out", default="topology_cache.py")
    args = p.parse_args()

    adjacency, all_nodes, rsu_layout, rsu_neighbors = build_topology(
        args.net, args.rsu_count, args.seed)
    write_cache(adjacency, all_nodes, rsu_layout, rsu_neighbors, args.out)

    print(f"\nTotal: {len(all_nodes)} nodes, {sum(len(v) for v in adjacency.values())} directed edges, "
          f"{len(rsu_layout)} RSU regions")
